# Generated by Django 4.2.20 on 2025-03-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catogory',
            new_name='category',
        ),
    ]
