# Generated by Django 4.2.20 on 2025-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_boutique', '0003_rename_name_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
