# Generated by Django 4.2.20 on 2025-03-26 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_boutique', '0005_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, help_text='Le mot de passe doit contenir au moins 12 caractères.', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
